sudo: false
language: c++

addons:
  apt:
    packages:
      - g++-6
      - gcc-6
      - cmake
      - cmake-data
    sources:
      - george-edison55-precise-backports
      
matrix:
  include:      
    - compiler: gcc
      os: linux
      env: COMPILER=g++6    
    - compiler: clang
      os: osx
      osx_image: xcode7
      env: COMPILER=clang++      

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake   ; fi
  
before_script:  
  - mkdir build/os
  - cd build/os
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ../..
  
script:
  - cd build/os && make 
  - cd ../../dist
  - ./SystemAPITest
  - ./SystemConformanceTest
  - ./UnitTest