if(WIN32)
    OPTION(RADONFRAMEWORK_USE_RENDERING_DWM "Activate rendering support for DWM" ON)
    mark_as_advanced(RADONFRAMEWORK_USE_RENDERING_DWM)
    
    if(RADONFRAMEWORK_USE_RENDERING_DWM)
        OPTION(RADONFRAMEWORK_STATICLINK_RENDERING_DWM "The DWM rendering support will be linked into the static lib." OFF)
        mark_as_advanced(RADONFRAMEWORK_STATICLINK_RENDERING_DWM)
    endif()
    
    set(LibTypeDWM "")
    if(RADONFRAMEWORK_STATICLINK_RENDERING_DWM)
        set(LibTypeDWM MODULE)
    else()
        set(LibTypeDWM SHARED)
    endif()
    
    AddSourceDirectoryRecursive(filelist "${CMAKE_CURRENT_LIST_DIR}" "Sources")
    list(APPEND RF_RENDERING_DWM_FILES ${filelist})	
    AddHeaderDirectoryRecursive(filelist "${CMAKE_CURRENT_LIST_DIR}" "Includes")
    list(APPEND RF_RENDERING_DWM_FILES ${filelist})		
    if(RADONFRAMEWORK_STATICLINK_RENDERING_DWM)
        list(REMOVE_ITEM RF_RENDERING_DWM_FILES "${CMAKE_CURRENT_LIST_DIR}/Shared.cpp")
    endif()
    Generate(${LibTypeDWM} RF_RENDERING_DWM RenderingDWM "Framework")
    AddPublicInclude(RF_RENDERING_DWM "${CMAKE_CURRENT_LIST_DIR}")
    AddDependency(RF_RENDERING_DWM RadonFramework)
    Finalize(RF_RENDERING_DWM)
endif()