if(WIN32)
    OPTION(RADONFRAMEWORK_USE_RENDERING_DWM "Activate rendering support for DWM" ON)
    mark_as_advanced(RADONFRAMEWORK_USE_RENDERING_DWM)
    
    if(RADONFRAMEWORK_USE_RENDERING_DWM)
        OPTION(RADONFRAMEWORK_STATICLINK_RENDERING_DWM "The DWM rendering support will be linked into the static lib." OFF)
        mark_as_advanced(RADONFRAMEWORK_STATICLINK_RENDERING_DWM)
    endif()
    
    set(LibTypeDWM "")
    if(RADONFRAMEWORK_STATICLINK_RENDERING_DWM)
        set(LibTypeDWM MODULE)
        rcf_add_internal(RADONFRAMEWORK_STATIC_SERVICE_TARGETS RF_RENDERING_DWM)
        rcf_remove_internal(RADONFRAMEWORK_DYNAMIC_SERVICE_TARGETS RenderingDWM)        
    else()
        set(LibTypeDWM SHARED)
        rcf_add_internal(RADONFRAMEWORK_DYNAMIC_SERVICE_TARGETS RenderingDWM)
        rcf_remove_internal(RADONFRAMEWORK_STATIC_SERVICE_TARGETS RF_RENDERING_DWM)    
    endif()
    
    AddSourceDirectory(filelist "${CMAKE_CURRENT_LIST_DIR}/../" "Sources")
    list(APPEND RF_RENDERING_DWM_FILES ${filelist})	
    AddHeaderDirectory(filelist "${CMAKE_CURRENT_LIST_DIR}/../" "Includes")
    list(APPEND RF_RENDERING_DWM_FILES ${filelist})	
    AddSourceDirectoryRecursive(filelist "${CMAKE_CURRENT_LIST_DIR}" "Sources")
    list(APPEND RF_RENDERING_DWM_FILES ${filelist})	
    AddHeaderDirectoryRecursive(filelist "${CMAKE_CURRENT_LIST_DIR}" "Includes")
    list(APPEND RF_RENDERING_DWM_FILES ${filelist})		
    if(RADONFRAMEWORK_STATICLINK_RENDERING_DWM)
        list(REMOVE_ITEM RF_RENDERING_DWM_FILES "${CMAKE_CURRENT_LIST_DIR}/Shared.cpp")
    endif()
    set(RF_RENDERING_DWM_LIBS OpenGL32)
    Generate(${LibTypeDWM} RF_RENDERING_DWM RenderingDWM "Framework")
    AddPublicInclude(RF_RENDERING_DWM "${CMAKE_CURRENT_LIST_DIR};${CMAKE_CURRENT_LIST_DIR}/../")
    AddDependency(RF_RENDERING_DWM RadonFramework)
    Finalize(RF_RENDERING_DWM)
endif()