export module rf.core.threading:thread;
import rf.core.types;
import :mutex;

export namespace rf {
struct TimeSpan;

enum class ThreadPriority { Minimal, Normal, Maximal };

class Thread {
public:
  static void Sleep(const TimeSpan &Delta);
  /// Return the Process ID of the current thread or main process.
  static u64 CurrentPid();

  Thread();
  ~Thread();

  /// This method will start the thread.
  void start();
  /// This method will stop the thread and wait till it's done.
  void exit();
  /// This method will stop the thread and return immediately.
  void interrupt();
  /// Return false if the thread is not alive or Exit/Interrupt was called else
  /// true.
  bool shouldRunning();
  /// Wait till the thread is dead.
  void join();
  void join(const TimeSpan &Delta);
  /// Return the thread priority.
  ThreadPriority getPriority();
  /// Set a new thread priority.
  void setPriority(ThreadPriority Value);
  /// Return the affinity mask.
  bool getAffinityMask(bits &Mask) const;
  /// Set the affinity mask.
  bool setAffinityMask(const bits &NewValue);
  /// Is the thread is running.
  bool isAlive();
  /// Return true if the backend is working.
  bool working();
  /// Assign a name to the thread, to make debugging easier.
  const strview &name() const;
  void name(const strview &NewName);
  /// ProcessID
  u64 pid() const;
  /// Allocate memory and assign it to the Thread.
  /// If the tread die and the memory isn't freed till yet then it will
  /// be cleaned up by the destructor.
  ptr memAlloc(u64 Bytes);
  /// Free allocated memory, if it was generated by an instance of this
  /// Thread class.
  void freeMem(constptr Ptr);
  /// Return true if the pointer is part of the allocated memory of
  /// a Thread instances.
  bool memAccess(constptr Ptr);
  /// This function will be called from the dying thread.
  virtual void finished();
  /// This function will be called from the thread to run multi threaded code.
  virtual void run();

protected:
  ThreadPriority priority = ThreadPriority::Normal;
  mem m_AffinityMask;
  mem m_ThreadAllocatedMemory;
  Mutex m_ThreadBarrier;
  str m_Name;
  u64 m_Pid = 0xffffffffffffffffull;
  ptr m_ImplData = nullptr;
  bool m_Alive;
};
} // namespace rf