if(WIN32)
    OPTION(RADONFRAMEWORK_USE_RENDERING_GDI "Activate rendering support for GDI" ON)
    mark_as_advanced(RADONFRAMEWORK_USE_RENDERING_GDI)
    
    if(RADONFRAMEWORK_USE_RENDERING_GDI)
        OPTION(RADONFRAMEWORK_STATICLINK_RENDERING_GDI "The GDI rendering support will be linked into the static lib." OFF)
        mark_as_advanced(RADONFRAMEWORK_STATICLINK_RENDERING_GDI)
    endif()
    
    set(LibTypeGDI "")
    if(RADONFRAMEWORK_STATICLINK_RENDERING_GDI)
        set(LibTypeGDI MODULE)
    else()
        set(LibTypeGDI SHARED)
    endif()
    
    set(RF_RENDERING_GDI_FILES "")
    AddSourceDirectoryRecursive(filelist "${CMAKE_CURRENT_LIST_DIR}" "Sources")
    list(APPEND RF_RENDERING_GDI_FILES ${filelist})	
    AddHeaderDirectoryRecursive(filelist "${CMAKE_CURRENT_LIST_DIR}" "Includes")
    list(APPEND RF_RENDERING_GDI_FILES ${filelist})		
    if(RADONFRAMEWORK_STATICLINK_RENDERING_GDI)
        list(REMOVE_ITEM RF_RENDERING_DWM_FILES "${CMAKE_CURRENT_LIST_DIR}/Shared.cpp")
    endif()
    Generate(${LibTypeGDI} RF_RENDERING_GDI RenderingGDI "Framework")
    AddPublicInclude(RF_RENDERING_GDI "${CMAKE_CURRENT_LIST_DIR}")
    AddDependency(RF_RENDERING_GDI RadonFramework)
    Finalize(RF_RENDERING_GDI)
endif()